site:
  title: Instituto de Física - UNAM
  url: http://fisica.unam.mx

cookie:
  domain: foo.com
  key: _ldap_change_password
  secret: 52d737e54b7c19af1c06c7101e405f842645b5c9446acd9cfa70bbdebf6aada443bb35460a5af20e3f93d567e59999fd6bd1d78ccc865b961c84318b4ebbf308

locale: en

helpdesk:
  title: Soporte técnico
  url: http://soporte.fisica.unam.mx
  phone: 56 22 50 01
