## Authorizations
#
# Uncomment out the merging for each enviornment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# enviornment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=people,dc=subdomain,dc=domain,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  # required_groups:
    # - cn=admins,ou=groups,dc=test,dc=com
    # - cn=users,ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: InetLocalMailRecipient,inetOrgPerson,organizationalPerson,person,top
    # authorizationRole: yourrole

## Environments

development:
  host: ldap.subdomain.domain.com
  port: 389
  attribute: uid
  base: ou=people,dc=subdomain,dc=domain,dc=com
  admin: true
  admin_user: cn=admin,dc=subdomain,dc=domain,dc=com
  admin_password: supersecurepw
  ssl: false
  <<: *AUTHORIZATIONS

test:
  host: ldap.subdomain.domain.com
  port: 3389
  attribute: uid
  base: ou=people,dc=subdomain,dc=domain,dc=com
  admin: true
  admin_user: cn=admin,dc=subdomain,dc=domain,dc=com
  admin_password: supersecurepw
  ssl: false
  # <<: *AUTHORIZATIONS

production:
  host: ldap.subdomain.domain.com
  port: 636
  attribute: uid
  base: ou=people,dc=subdomain,dc=domain,dc=com
  admin: true
  admin_user: cn=admin,dc=subdomain,dc=domain,dc=com
  admin_password: supersecurepw
  ssl: true
  <<: *AUTHORIZATIONS
